name = "chunge-space"
compatibility_date = "2025-01-01"
compatibility_flags = ["nodejs_compat"]

[[d1_databases]]
binding = "DB"
database_name = "chunge-space-db"
database_id = "7ee2eec1-da26-4167-b2df-dddf7e7b2edf"
